#!/bin/bash
#PBS -A hpc_brumbird15
#PBS -l nodes=1:ppn=20
#PBS -l walltime=72:00:00
#PBS -q checkpt
#PBS -N filter


module load vcftools/0.1.14/INTEL-18.0.0
cd /work/rmarco3

vcftools \
    --gzvcf total_vcf_pre_vqsr.vcf.gz \
    --minDP 30 \
    --minQ 30 \
    --minGQ 30 \
    --max-alleles 2 \
    --remove-indels \
    --max-missing 0.5 \
    --out hi-q-vars
